name: YouTube Videos to Social Media
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        id: blog-post-workflow
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCjHMUEzoCauYet8NG4sCog"
          max_post_count: 1
          output_only: true
      - run:  TITLE = ${{ steps.blog-post-workflow.outputs.results }}
      - uses: sergeysova/jq-action@v2
        id: jq
        with:
          cmd: echo $TITLE | jq '.[].title'
