name: YouTube Videos to Social Media
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: blog
      - uses: gautamkrishnar/blog-post-workflow@master
        id: blog-post-workflow
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCjHMUEzoCauYet8NG4sCog"
          max_post_count: 1
          output_only: true
      - run:  echo ::set-output name=json_var::'{{ steps.blog-post-workflow.outputs.results }} ' 
      - name: use output
        run: |
          echo $json_var | jq '.[].title'
        env:
          json_var: ${{ steps.set.outputs.json_var}}
